# conda env create --file environment.yml
name: {{cookiecutter.project_slug}}

channels:
  - conda-forge
  - defaults

dependencies:
  - python={{cookiecutter.python_version}}
  - pip
  - pip:
    - -r requirements.txt
